In [2]:
"""pytorch samples"""
import torch
import numpy as np

print(torch.__version__)
print(np.__version__)

my_list = np.random.rand(3, 4)
print(my_list)
print(my_list.shape)
print(my_list.dtype)

tensor = torch.rand(3, 4)

print(tensor)

tensor_1 = torch.zeros(2, 3, 4,)
print(tensor_1)

print(torch.tensor(my_list))


2.4.1
1.26.4
[[0.97285596 0.71689575 0.92249998 0.01929544]
 [0.24148057 0.29752711 0.61897464 0.70537364]
 [0.44302459 0.19776302 0.78909429 0.0149641 ]]
(3, 4)
float64
tensor([[0.4747, 0.9304, 0.2281, 0.4953],
        [0.9643, 0.5852, 0.4753, 0.6896],
        [0.1282, 0.2615, 0.3631, 0.1788]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[0.9729, 0.7169, 0.9225, 0.0193],
        [0.2415, 0.2975, 0.6190, 0.7054],
        [0.4430, 0.1978, 0.7891, 0.0150]], dtype=torch.float64)


In [6]:
import torch

my_torch = torch.arange(10)
print(my_torch)
my_torch = my_torch.reshape(2, 5)
print(my_torch)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
